[package]
name = "pom"
version = "0.1.0"
authors = ["jest"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
structopt = "0.3.5"
chrono = "0.4"
dirs = "2.0.2"
ctrlc = "3.1.3"
rodio = "0.10.0"